# Server
server.port=${PORT:8080}
server.address=0.0.0.0

# PostgreSQL (Render DB)
spring.datasource.url=jdbc:postgresql://dpg-d72815h5pdvs73dhbkb0-a.oregon-postgres.render.com:5432/manpower_thn5
spring.datasource.username=manpower_user
spring.datasource.password=VFK9Tf4cLF5S57utl4N6tZc9E2oZ6D7f
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.connection-timeout=30000

logging.level.org.springframework=DEBUG