# Server
server.port=${PORT:8080}
server.address=0.0.0.0

# PostgreSQL (Render DB)
spring.datasource.url=postgresql://manpower_user:VFK9Tf4cLF5S57utl4N6tZc9E2oZ6D7f@dpg-d72815h5pdvs73dhbkb0-a/manpower_thn5
spring.datasource.username=manpower_user
spring.datasource.password=VFK9Tf4cLF5S57utl4N6tZc9E2oZ6D7f
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true